/* Query to Find the total revenue generated by each employee */

SELECT e.employee_id, CONCAT(e.first_name, ' ', e.last_name) AS employee_name, SUM(od.quantity * od.unit_price) AS total_revenue
FROM employees e
JOIN orders o ON e.employee_id = o.employee_id
JOIN order_details od ON o.order_id = od.order_id
GROUP BY e.employee_id, employee_name;
